name: eng_mhamdino_flutter_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

  golden_toolkit: ^0.15.0
  equatable: ^2.0.5
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  uuid: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0

  url_launcher: ^6.3.0
  flutter_bloc: ^9.1.0
  shimmer: ^3.0.0
  mockito: ^5.3.2
  multi_dropdown:
  omni_datetime_picker:
  file_picker:

  date_picker_plus: ^3.0.2
  shared:
    path: packages/shared
  ui:
    path: packages/ui
  api_service:
    path: packages/api_service
  dialog_services:
    path: packages/dialog_services
  flutter_bug_logger: ^1.0.0

  nested: ^1.0.0
  line_icons: ^2.0.3
  path_provider: ^2.0.15
  permission_handler:

  flutter_widget_from_html_core: ^0.16.0
  change_app_package_name: ^1.4.0

  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.6.1
  objectbox_generator: ^4.3.0
  build_runner: ^2.4.11
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  melos: ^3.1.0
  flutter_gen: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.0.1
  device_info_plus: ^10.1.1
  flutter_gen_runner: ^5.8.0
  expansion_tile_list:

    # Mocking
  mocktail:

  # BLoC Test Utilities
  bloc_test:

  test:

dependency_overrides:
  device_info_plus: ^10.1.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eng_mhamdino.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/jsons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
